variables:
  homepage: https://github.com/caarlos0/fastcom-exporter
  description: Exports Fast.com results to the Prometheus format
includes:
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/build.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/release.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/podman.yml

before:
  hooks:
    - go mod tidy
nfpms:
  - vendor: Becker Software LTDA
    homepage: '{{ .homepage }}'
    maintainer: Carlos Alexandro Becker <carlos@becker.software>
    description: '{{ .description }}'
    formats:
      - apk
      - deb
      - rpm

brews:
- tap:
    owner: caarlos0
    name: homebrew-tap
  folder: Formula
  description: '{{ .description }}'
  homepage: '{{ .homepage }}'
  dependencies:
    - name: speedtest

furies:
- account: caarlos0
